version: '3.7'

services:
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ayushyadav99/ecomapp-server
    container_name: ecomapp-node-server
    command: ./node_modules/.bin/nodemon ./backend/server.js 
    volumes:
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ayushyadav99/ecomapp-client
    container_name: ecomapp-react-client
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
