---
- name: Pull docker image 
  hosts: all 
  connection: local
  tasks:
    - name: Pull frontend image
      docker_image:
        name: ayushyadav99/ecomapp-client
        source: pull
    - name: Pull backend image
      docker_image:
        name: ayushyadav99/ecomapp-server
        source: pull
